import { Staff, Task } from "@/GanttScheduler/types"
import { AVATAR_COLOR_CLASSES } from "@/GanttScheduler/utils/constants"

export const MOCK_ROLE_DATA = ["特效师", "合成师", "动画师", "模型师", "导演", "前端工程师", "后端工程师", "测试工程师", "产品经理", "设计师", "项目经理", "运营经理", "客户服务代表"]
const MOCK_SURNAMES = ["张", "王", "李", "赵", "刘", "陈", "杨", "黄", "周", "吴", "徐", "孙", "马", "朱", "胡", "郭", "何", "高", "林", "郑", "罗", "梁", "宋", "谢", "唐", "许", "韩", "冯", "邓", "曹", "彭", "曾", "肖", "田", "董", "袁", "潘", "于", "蒋", "蔡", "余", "杜", "叶", "程", "苏", "魏", "吕", "丁", "任", "沈", "姚", "卢", "姜", "崔", "钟", "谭", "陆", "汪", "范", "金", "石", "廖", "贾", "夏", "韦", "付", "方", "白", "邹", "孟", "熊", "秦", "邱", "江", "尹", "薛", "闫", "段", "雷", "侯", "龙", "史", "陶", "黎", "贺", "顾", "毛", "郝", "龚", "邵", "万", "钱", "严", "覃", "武", "戴", "莫", "孔", "向"]
const MOCK_GIVEN_NAMES = [
  "伟",
  "芳",
  "娜",
  "秀英",
  "敏",
  "静",
  "丽",
  "强",
  "磊",
  "军",
  "洋",
  "勇",
  "艳",
  "杰",
  "娟",
  "涛",
  "明",
  "超",
  "秀兰",
  "霞",
  "平",
  "刚",
  "桂英",
  "文",
  "华",
  "建",
  "红",
  "玉",
  "云",
  "鹏",
  "兰",
  "飞",
  "斌",
  "倩",
  "健",
  "俊",
  "帆",
  "雪",
  "梅",
  "宁",
  "琳",
  "波",
  "丹",
  "浩",
  "坤",
  "婷",
  "慧",
  "旭",
  "阳",
  "畅",
  "欣",
  "璇",
  "博",
  "瑞",
  "佳",
  "鑫",
  "梦",
  "甜",
  "翊",
  "宸",
  "昊",
  "梓",
  "轩",
  "宇",
  "泽",
  "睿",
  "嘉",
  "思",
  "怡",
  "辰",
  "萱",
  "俊杰",
  "浩然",
  "子轩",
  "梓轩",
  "浩宇",
  "俊宇",
  "梓睿",
  "一诺",
  "依诺",
  "欣怡",
  "梓涵",
  "诗涵",
  "可欣",
  "语桐",
  "欣妍",
  "雨泽",
  "明轩",
  "浩轩",
  "梓晨",
  "宇轩",
  "皓轩",
  "子涵",
  "雨涵",
  "晨曦",
  "子墨",
  "紫涵",
  "若曦",
  "思源",
  "思远",
  "浩南",
  "浩东",
  "宇航",
  "天佑",
  "俊熙",
  "子豪",
  "天宇",
  "文博",
  "文昊",
  "峻熙",
  "致远",
  "俊楠",
  "弘文",
  "伟祺",
  "荣轩",
  "楷瑞",
  "建辉",
  "晋鹏",
  "天磊",
  "绍辉",
  "泽洋",
  "鑫鹏",
  "昊强",
  "伟宸",
  "博超",
  "君浩",
  "子骞",
  "鹏涛",
  "炎彬",
  "鹤轩",
  "越彬",
  "风华",
  "靖琪",
  "明辉",
  "伟诚",
  "明轩",
  "健柏",
  "修杰",
  "志泽",
  "弘昌",
  "峻熙",
  "煜祺",
  "智宸",
  "正豪",
  "昊然",
  "明杰",
  "立诚",
  "立轩",
  "立辉",
  "熠彤",
  "鸿煊",
  "烨霖",
  "哲瀚",
  "鑫鹏",
  "昊天",
  "思聪",
  "展鹏",
  "笑愚",
  "志强",
  "炫明",
  "雪松",
  "思源",
  "智渊",
  "思淼",
  "晓啸",
  "天宇",
  "浩然",
  "文轩",
  "鹭洋",
  "振家",
  "乐驹",
  "晓博",
  "文博",
  "昊焱",
  "立果",
  "金鑫",
  "锦程",
  "嘉熙",
  "鹏飞",
  "子默",
  "思远",
  "浩轩",
  "语堂",
  "聪健",
]
const getMockName = (): string => {
  const s = MOCK_SURNAMES[Math.floor(Math.random() * MOCK_SURNAMES.length)]
  const g = MOCK_GIVEN_NAMES[Math.floor(Math.random() * MOCK_GIVEN_NAMES.length)]
  return `${s}${g}`
}
export const MOCK_STAFF_AVATAR_DATA = ["https://api.dicebear.com/7.x/avataaars/svg?seed=Felix", "https://api.dicebear.com/7.x/avataaars/svg?seed=Max", "https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie", "https://api.dicebear.com/7.x/avataaars/svg?seed=Cooper", "https://api.dicebear.com/7.x/avataaars/svg?seed=Daisy", "https://api.dicebear.com/7.x/avataaars/svg?seed=Oscar", "https://api.dicebear.com/7.x/avataaars/svg?seed=Millie", "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucy"]
export const MOCK_TASK_NAME_DATA = ["项目管理中心", "采购部", "项目管理办公室", "IP开发部", "展陈部", "品宣业务中心", "售前三部", "导演部", "两点十分文化", "总经办", "营销中心", "客户售前一部", "客户售前二部", "财务中心", "综合中心", "制片中心", "供应链中心", "文创产品中心", "市场运营中心", "研发中心", "AI创制中心", "品牌宣发中心", "业务增长部", "品宣策划部", "企业发展中心", "公共事务部", "幻彩工作室", "智绘工作室", "牧云工作室", "时光工作室", "起飞工作室", "雷霆工作室", "ACE工作室", "鱼渊工作室", "拂晓教育中心", "创引力文化", "MIX工作室", "蓝鲸工作室", "星光工作室", "梵星工作室", "可意工作室", "加法工作室", "星辰十分", "银行", "制作税点", "制包", "跨界自包", "心智网络", "-----以下是老数据，慎用-----", "种梦工作室", "组织流程部", "跨界供应链中心", "教育中心", "声光记", "策创中心", "一视工作室", "十方工作室", "仙禄文化", "时帧", "包装工作室", "燃梦文化", "客户售前部", "十二色", "独角兽"]

// Helper to create dates relative to today
const getRelativeDate = (offsetDays: number) => {
  const d = new Date()
  d.setDate(d.getDate() + offsetDays)
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, "0")
  const day = String(d.getDate()).padStart(2, "0")
  return `${y}-${m}-${day}`
}

export const getMockStaffData = (count: number = 0): Staff[] => {
  count = count || Math.ceil(Math.random() * 50)
  let taskCount = 1
  return Array.from({ length: count }, (_, index) => ({
    uid: `${index + 1}`,
    id: index + 1,
    name: getMockName(),
    role: MOCK_ROLE_DATA[Math.floor(Math.random() * MOCK_ROLE_DATA.length)],
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: AVATAR_COLOR_CLASSES[Math.floor(Math.random() * AVATAR_COLOR_CLASSES.length)],
    workloadPercentage: Math.ceil(Math.random() * 100),
    isCollapsed: false,
    tasks: Array.from(
      { length: Math.ceil(Math.random() * 10) },
      (_, i) =>
        ({
          uid: `T${(taskCount++).toString().padStart(4, "0")}`,
          id: i + 1,
          name: MOCK_TASK_NAME_DATA[Math.floor(Math.random() * MOCK_TASK_NAME_DATA.length)],
          startDate: getRelativeDate(Math.random() < 0.3 ? -Math.ceil(Math.random() * 100) : Math.ceil(Math.random() * 100)),
          duration: Math.ceil(Math.random() * 30),
          rowOffset: Math.floor(Math.random() * 10),
        } as Task)
    ),
  }))
}

export const REAL_STAFF_DATA: Staff[] = [
  {
    uid: "1",
    id: 1,
    name: "尼古丁",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "mm政企项目1202(EMMAZZ)",
        startDate: "2025-12-16",
        duration: 15,
        rowOffset: 0,
      },
      {
        uid: "T0001",
        id: 2,
        name: "Gaijin皮肤CG2(GJCAYZ)",
        startDate: "2025-09-16",
        duration: 185,
        rowOffset: 1,
      },
    ],
  },
  {
    uid: "2",
    id: 2,
    name: "云吞面",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "mm政企项目1202(EMMAZZ)",
        startDate: "2025-12-16",
        duration: 15,
        rowOffset: 0,
      },
      {
        uid: "T0001",
        id: 2,
        name: "Gaijin皮肤CG2(GJCAYZ)",
        startDate: "2025-09-16",
        duration: 185,
        rowOffset: 1,
      },
      {
        uid: "T0002",
        id: 3,
        name: "售前外包项目0906940(SIOAYZ)",
        startDate: "2025-09-30",
        duration: 123,
        rowOffset: 2,
      },
      {
        uid: "T0003",
        id: 4,
        name: "平台杯雪番剧正片(SKCBPZ)",
        startDate: "2023-04-27",
        duration: 979,
        rowOffset: 3,
      },
      {
        uid: "T0004",
        id: 5,
        name: "手机端测试分店正片(WPPAPZ)",
        startDate: "2025-11-02",
        duration: 93,
        rowOffset: 4,
      },
      {
        uid: "T0005",
        id: 6,
        name: "手机端测试分店正片(WPPAPZ)",
        startDate: "2025-11-02",
        duration: 93,
        rowOffset: 5,
      },
    ],
  },
  {
    uid: "3",
    id: 3,
    name: "火龙果",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "售前外包项目0906940(SIOAYZ)",
        startDate: "2025-09-30",
        duration: 123,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "4",
    id: 4,
    name: "三川",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "入账测试项目1010(YMLBYZ)",
        startDate: "2025-06-11",
        duration: 203,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "5",
    id: 5,
    name: "洋鸽",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "入账测试项目1010(YMLBYZ)",
        startDate: "2025-06-11",
        duration: 203,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "6",
    id: 6,
    name: "雾海",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "云顶新春2026(YXLAYZ)",
        startDate: "2025-08-22",
        duration: 146,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "7",
    id: 7,
    name: "黄鱼",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "云顶新春2026(YXLAYZ)",
        startDate: "2025-08-22",
        duration: 146,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "8",
    id: 8,
    name: "梨也",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "mm政企项目1202(EMMAZZ)",
        startDate: "2025-12-16",
        duration: 15,
        rowOffset: 0,
      },
      {
        uid: "T0001",
        id: 2,
        name: "Gaijin皮肤CG2(GJCAYZ)",
        startDate: "2025-09-16",
        duration: 185,
        rowOffset: 1,
      },
      {
        uid: "T0002",
        id: 3,
        name: "售前外包项目0906940(SIOAYZ)",
        startDate: "2025-09-30",
        duration: 123,
        rowOffset: 2,
      },
      {
        uid: "T0003",
        id: 4,
        name: "meizi外币项目(TYTBYZ)",
        startDate: "2025-06-17",
        duration: 185,
        rowOffset: 3,
      },
      {
        uid: "T0004",
        id: 5,
        name: "思彤预留款项目1015(WCRAYZ)",
        startDate: "2025-10-21",
        duration: 119,
        rowOffset: 4,
      },
      {
        uid: "T0005",
        id: 6,
        name: "jg外币项目1211(WQBAYZ)",
        startDate: "2025-11-07",
        duration: 118,
        rowOffset: 5,
      },
      {
        uid: "T0006",
        id: 7,
        name: "jg外币项目1211(WQBAYZ)",
        startDate: "2025-11-07",
        duration: 118,
        rowOffset: 6,
      },
    ],
  },
  {
    uid: "9",
    id: 9,
    name: "天天",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "mm政企项目1202(EMMAZZ)",
        startDate: "2025-12-16",
        duration: 15,
        rowOffset: 0,
      },
      {
        uid: "T0001",
        id: 2,
        name: "mm政企项目1202(EMMAZZ)",
        startDate: "2025-12-16",
        duration: 15,
        rowOffset: 1,
      },
      {
        uid: "T0002",
        id: 3,
        name: "Gaijin皮肤CG2(GJCAYZ)",
        startDate: "2025-09-16",
        duration: 185,
        rowOffset: 2,
      },
      {
        uid: "T0003",
        id: 4,
        name: "售前外包项目0906940(SIOAYZ)",
        startDate: "2025-09-30",
        duration: 123,
        rowOffset: 3,
      },
      {
        uid: "T0004",
        id: 5,
        name: "思彤预留款项目1015(WCRAYZ)",
        startDate: "2025-10-21",
        duration: 119,
        rowOffset: 4,
      },
      {
        uid: "T0005",
        id: 6,
        name: "手机端测试分店正片(WPPAPZ)",
        startDate: "2025-11-02",
        duration: 93,
        rowOffset: 5,
      },
      {
        uid: "T0006",
        id: 7,
        name: "手机端测试分店正片(WPPAPZ)",
        startDate: "2025-11-02",
        duration: 93,
        rowOffset: 6,
      },
      {
        uid: "T0007",
        id: 8,
        name: "WR告白气球CG(WRGAYZ)",
        startDate: "2025-12-02",
        duration: 61,
        rowOffset: 7,
      },
    ],
  },
  {
    uid: "10",
    id: 10,
    name: "大橡",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "mm政企项目1202(EMMAZZ)",
        startDate: "2025-12-16",
        duration: 15,
        rowOffset: 0,
      },
      {
        uid: "T0001",
        id: 2,
        name: "Gaijin皮肤CG2(GJCAYZ)",
        startDate: "2025-09-16",
        duration: 185,
        rowOffset: 1,
      },
    ],
  },
  {
    uid: "11",
    id: 11,
    name: "海里",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "Gaijin皮肤CG2(GJCAYZ)",
        startDate: "2025-09-16",
        duration: 185,
        rowOffset: 0,
      },
      {
        uid: "T0001",
        id: 2,
        name: "入账测试项目1010(YMLBYZ)",
        startDate: "2025-06-11",
        duration: 203,
        rowOffset: 1,
      },
    ],
  },
  {
    uid: "12",
    id: 12,
    name: "丹子",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "平台杯雪番剧正片(SKCBPZ)",
        startDate: "2023-04-27",
        duration: 979,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "13",
    id: 13,
    name: "瑀辰",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "平台杯雪番剧正片(SKCBPZ)",
        startDate: "2023-04-27",
        duration: 979,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "14",
    id: 14,
    name: "飞龙",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "平台杯雪番剧正片(SKCBPZ)",
        startDate: "2023-04-27",
        duration: 979,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "15",
    id: 15,
    name: "乔木",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "思彤预留款项目1015(WCRAYZ)",
        startDate: "2025-10-21",
        duration: 119,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "16",
    id: 16,
    name: "老王",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "外币项目1113(WNNCYZ)",
        startDate: "2025-08-12",
        duration: 183,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "17",
    id: 17,
    name: "博衍",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "WR告白气球CG(WRGAYZ)",
        startDate: "2025-12-02",
        duration: 61,
        rowOffset: 0,
      },
    ],
  },
  {
    uid: "18",
    id: 18,
    name: "灵犀",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "云顶新春2026(YXLAYZ)",
        startDate: "2025-08-22",
        duration: 146,
        rowOffset: 0,
      },
      {
        uid: "T0001",
        id: 2,
        name: "云顶新春2026(YXLAYZ)",
        startDate: "2025-08-22",
        duration: 146,
        rowOffset: 1,
      },
    ],
  },
  {
    uid: "19",
    id: 19,
    name: "坚果",
    avatar: Math.random() > 0.5 ? MOCK_STAFF_AVATAR_DATA[Math.floor(Math.random() * MOCK_STAFF_AVATAR_DATA.length)] : "",
    avatarColor: "bg-blue-100 text-blue-600",
    isCollapsed: false,
    tasks: [
      {
        uid: "T0000",
        id: 1,
        name: "云顶新春2026(YXLAYZ)",
        startDate: "2025-08-22",
        duration: 146,
        rowOffset: 0,
      },
    ],
  },
]
